from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from .findings import SafetyFinding, EvidenceSource


DISCLAIMER = (
    "This medication safety review is generated by an AI research assistant for "
    "informational purposes only. It does not constitute medical advice, diagnosis, "
    "or treatment recommendations. Always consult a qualified healthcare professional "
    "before making any changes to your medications."
)


class SafetyReport(BaseModel):
    review_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    medications_reviewed: list[str]
    patient_age: int
    patient_conditions: list[str]

    findings: list[SafetyFinding] = Field(default_factory=list)
    evidence_summary: list[EvidenceSource] = Field(default_factory=list)
    additional_information: list[str] = Field(default_factory=list)

    total_findings: int = Field(default=0)
    high_severity_count: int = Field(default=0)
    moderate_severity_count: int = Field(default=0)
    low_severity_count: int = Field(default=0)

    research_retries: int = Field(default=0)
    agent_steps_completed: list[str] = Field(default_factory=list)

    disclaimer: str = Field(default=DISCLAIMER)

    def model_post_init(self, __context) -> None:
        self.total_findings = len(self.findings)
        self.high_severity_count = sum(1 for f in self.findings if f.severity.value in ("high", "critical"))
        self.moderate_severity_count = sum(1 for f in self.findings if f.severity.value == "moderate")
        self.low_severity_count = sum(1 for f in self.findings if f.severity.value == "low")
